Models/ErrorViewModel.cs
namespace ListaMVCMoveisAlan.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ModelsView/ItemModelView.cs
namespace ListaMVCMoveisAlan.Models.ModelsView
{
    public class ItemModelView
    {
        public string nomeMoveis { get; set; }

        public bool checkMoveis { get; set; }

        public ItemModelView(string nomeMoveis, bool checkMoveis)
        {
            this.nomeMoveis = nomeMoveis;
            this.checkMoveis = checkMoveis;
        }

        public ItemModelView()
        {


        }
    }
}

Controllers/HomeController.cs
using ListaMVCMoveisAlan.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ListaMVCMoveisAlan.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MoveisController.cs
using ListaMVCMoveisAlan.Models.ModelsView;
using Microsoft.AspNetCore.Mvc;

namespace ListaMVCMoveisAlan.Controllers
{
    public class MoveisController : Controller
    {
        public IActionResult ListaMoveis()
        {
            List<ItemModelView> itemModelViews = new List<ItemModelView>();
            itemModelViews.Add(new ItemModelView("Porta", true));
            itemModelViews.Add(new ItemModelView("Janela", true));
            itemModelViews.Add(new ItemModelView("Cadeira", false));
            itemModelViews.Add(new ItemModelView("Cama", false));
            itemModelViews.Add(new ItemModelView("Sofá", true));
            itemModelViews.Add(new ItemModelView("Mesa", false));
            itemModelViews.Add(new ItemModelView("Poltrona", true));
            itemModelViews.Add(new ItemModelView("Fogão", true));
            itemModelViews.Add(new ItemModelView("Microondas", true));
            itemModelViews.Add(new ItemModelView("Geladeira", false));
            itemModelViews.Add(new ItemModelView("Ventilador", true));
            itemModelViews.Add(new ItemModelView("Chaleira", false));
            return View(itemModelViews);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Moveis/ListaMoveis.cshtml
@model List<ItemModelView>

    <h3 class="fw-bolder"> Lista de móveis </h3>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome do Móvel</th>
                <th scope="col">Check</th>

            </tr>
        </thead>
        <tbody>
            @{
                var cont = 1;
            }
            @foreach (var item in Model)
            {
                <tr>
                    <td>@cont</td>
                    <td>@item.nomeMoveis</td>
                    <td>
                        <div class="form-check">
                            @if (item.checkMoveis)
                            {
                                <input class="form-check-input" type="checkbox" value="" checked>
                            }
                            else
                            {
                                <input class="form-check-input" type="checkbox" value="">
                            }

                        </div>
                    </td>
                </tr>
                cont++;

            }

        </tbody>
    </table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaMVCMoveisAlan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaMVCMoveisAlan.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ListaMVCMoveisAlan</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Moveis" asp-action="ListaMoveis">Móveis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ListaMVCMoveisAlan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>